group: bluezone
jobs:
  include:
    - language: python
      python: 3.12
      install:
        - echo -e "machine github.ibm.com\n  login $CI_USER_TOKEN" > ~/.netrc
        - python3 -m pip install -U pip
        - pip3 install importlib_metadata
        - pip3 install pyOpenSSL --upgrade
        - pip3 install --upgrade "git+https://github.com/ibm/detect-secrets.git@master#egg=detect-secrets"
      script:
        - detect-secrets scan --update .secrets.baseline
        - detect-secrets audit .secrets.baseline --report --fail-on-unaudited --omit-instructions  
    - language: go
      go: 1.21.3
      install:
        # Required to install detect-secrets
        - echo -e "machine github.ibm.com\n  login $CI_USER_TOKEN" > ~/.netrc
        - curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -d -b $GOPATH/bin
      before_script:
        - go vet $(go list ./... | grep -v "fixtures" | grep -v "vendor")
        - go test $(go list ./... | grep -v "fixtures" | grep -v "vendor")
        - gosec -exclude-dir=fixture -exclude-dir=plugin/resources -quiet ./...
      script:
        - go build

notifications:
  slack:
    rooms: ibm-cloudplatform:RZfnTv0P664KhVAtEAjcEBPJ
    on_failure: always
    on_success: change
