group: bluezone
language: go
go:
  - 1.19.3
addons:
  apt:
    packages:
      - python3 
      - python3-pip 
      - python3-setuptools
install:
  # Required to install detect-secrets
  - echo -e "machine github.ibm.com\n  login $CI_USER_TOKEN" > ~/.netrc
  #- sudo chmod o+rwx /usr/lib/python3/dist-packages/
  - sudo python3 -m pip install -U pip
  - sudo pip3 install --upgrade "git+https://github.com/ibm/detect-secrets.git@master#egg=detect-secrets"
  - curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $GOPATH/bin v2.8.1
before_script:
  - bash bin/catch-i18n-mismatch.sh
  - bash bin/generate-i18n-resources.sh
  - go vet $(go list ./... | grep -v "fixtures" | grep -v "vendor")
  - go test $(go list ./... | grep -v "fixtures" | grep -v "vendor")
  - python3 bin/detect_secrets.py
  
  - gosec -exclude-dir=fixture -exclude-dir=plugin/resources -quiet ./...
script:
  - go build
notifications:
  slack:
    rooms: ibm-cloudplatform:RZfnTv0P664KhVAtEAjcEBPJ
    on_failure: always
    on_success: change
