package order

import "github.com/softlayer/softlayer-go/datatypes"

var TYPEMAP = map[string]interface{}{

	"SoftLayer_Container_Product_Order_Account_Media_Data_Transfer_Request": &datatypes.Container_Product_Order_Account_Media_Data_Transfer_Request{},

	"SoftLayer_Container_Product_Order_Gateway_Appliance_Cluster":                        &datatypes.Container_Product_Order_Gateway_Appliance_Cluster{},
	"SoftLayer_Container_Product_Order_Hardware_Security_Module":                         &datatypes.Container_Product_Order_Hardware_Security_Module{},
	"SoftLayer_Container_Product_Order_Hardware_Server":                                  &datatypes.Container_Product_Order_Hardware_Server{},
	"SoftLayer_Container_Product_Order_Hardware_Server_Colocation":                       &datatypes.Container_Product_Order_Hardware_Server_Colocation{},
	"SoftLayer_Container_Product_Order_Hardware_Server_Gateway_Appliance":                &datatypes.Container_Product_Order_Hardware_Server_Gateway_Appliance{},
	"SoftLayer_Container_Product_Order_Hardware_Server_Upgrade":                          &datatypes.Container_Product_Order_Hardware_Server_Upgrade{},
	"SoftLayer_Container_Product_Order_Hardware_Server_Vpc":                              &datatypes.Container_Product_Order_Hardware_Server_Vpc{},
	"SoftLayer_Container_Product_Order_Monitoring_Package":                               &datatypes.Container_Product_Order_Monitoring_Package{},
	"SoftLayer_Container_Product_Order_MultiConfiguration":                               &datatypes.Container_Product_Order_MultiConfiguration{},
	"SoftLayer_Container_Product_Order_MultiConfiguration_Tornado":                       &datatypes.Container_Product_Order_MultiConfiguration_Tornado{},
	"SoftLayer_Container_Product_Order_Network_Application_Delivery_Controller":          &datatypes.Container_Product_Order_Network_Application_Delivery_Controller{},
	"SoftLayer_Container_Product_Order_Network_Interconnect":                             &datatypes.Container_Product_Order_Network_Interconnect{},
	"SoftLayer_Container_Product_Order_Network_Interconnect_Upgrade":                     &datatypes.Container_Product_Order_Network_Interconnect_Upgrade{},
	"SoftLayer_Container_Product_Order_Network_LoadBalancer":                             &datatypes.Container_Product_Order_Network_LoadBalancer{},
	"SoftLayer_Container_Product_Order_Network_LoadBalancer_AsAService":                  &datatypes.Container_Product_Order_Network_LoadBalancer_AsAService{},
	"SoftLayer_Container_Product_Order_Network_Message_Delivery":                         &datatypes.Container_Product_Order_Network_Message_Delivery{},
	"SoftLayer_Container_Product_Order_Network_PerformanceStorage":                       &datatypes.Container_Product_Order_Network_PerformanceStorage{},
	"SoftLayer_Container_Product_Order_Network_PerformanceStorage_Iscsi":                 &datatypes.Container_Product_Order_Network_PerformanceStorage_Iscsi{},
	"SoftLayer_Container_Product_Order_Network_PerformanceStorage_Nfs":                   &datatypes.Container_Product_Order_Network_PerformanceStorage_Nfs{},
	"SoftLayer_Container_Product_Order_Network_Protection_Firewall":                      &datatypes.Container_Product_Order_Network_Protection_Firewall{},
	"SoftLayer_Container_Product_Order_Network_Protection_Firewall_Dedicated":            &datatypes.Container_Product_Order_Network_Protection_Firewall_Dedicated{},
	"SoftLayer_Container_Product_Order_Network_Protection_Firewall_Dedicated_Upgrade":    &datatypes.Container_Product_Order_Network_Protection_Firewall_Dedicated_Upgrade{},
	"SoftLayer_Container_Product_Order_Network_Storage_AsAService":                       &datatypes.Container_Product_Order_Network_Storage_AsAService{},
	"SoftLayer_Container_Product_Order_Network_Storage_AsAService_Upgrade":               &datatypes.Container_Product_Order_Network_Storage_AsAService_Upgrade{},
	"SoftLayer_Container_Product_Order_Network_Storage_Backup_Evault_Plugin":             &datatypes.Container_Product_Order_Network_Storage_Backup_Evault_Plugin{},
	"SoftLayer_Container_Product_Order_Network_Storage_Backup_Evault_Vault":              &datatypes.Container_Product_Order_Network_Storage_Backup_Evault_Vault{},
	"SoftLayer_Container_Product_Order_Network_Storage_Enterprise":                       &datatypes.Container_Product_Order_Network_Storage_Enterprise{},
	"SoftLayer_Container_Product_Order_Network_Storage_Enterprise_SnapshotSpace":         &datatypes.Container_Product_Order_Network_Storage_Enterprise_SnapshotSpace{},
	"SoftLayer_Container_Product_Order_Network_Storage_Enterprise_SnapshotSpace_Upgrade": &datatypes.Container_Product_Order_Network_Storage_Enterprise_SnapshotSpace_Upgrade{},
	"SoftLayer_Container_Product_Order_Network_Storage_Hub":                              &datatypes.Container_Product_Order_Network_Storage_Hub{},
	"SoftLayer_Container_Product_Order_Network_Storage_Iscsi":                            &datatypes.Container_Product_Order_Network_Storage_Iscsi{},
	"SoftLayer_Container_Product_Order_Network_Storage_MassDataMigration_Request":        &datatypes.Container_Product_Order_Network_Storage_MassDataMigration_Request{},
	"SoftLayer_Container_Product_Order_Network_Storage_Modification":                     &datatypes.Container_Product_Order_Network_Storage_Modification{},
	"SoftLayer_Container_Product_Order_Network_Storage_Nas":                              &datatypes.Container_Product_Order_Network_Storage_Nas{},
	"SoftLayer_Container_Product_Order_Network_Storage_Object":                           &datatypes.Container_Product_Order_Network_Storage_Object{},
	"SoftLayer_Container_Product_Order_Network_Subnet":                                   &datatypes.Container_Product_Order_Network_Subnet{},
	"SoftLayer_Container_Product_Order_Network_Tunnel_Ipsec":                             &datatypes.Container_Product_Order_Network_Tunnel_Ipsec{},
	"SoftLayer_Container_Product_Order_Network_Vlan":                                     &datatypes.Container_Product_Order_Network_Vlan{},
	"SoftLayer_Container_Product_Order_NewCustomerSetup":                                 &datatypes.Container_Product_Order_NewCustomerSetup{},
	"SoftLayer_Container_Product_Order_Private_Cloud":                                    &datatypes.Container_Product_Order_Private_Cloud{},
	"SoftLayer_Container_Product_Order_Security_Certificate":                             &datatypes.Container_Product_Order_Security_Certificate{},
	"SoftLayer_Container_Product_Order_Service":                                          &datatypes.Container_Product_Order_Service{},
	"SoftLayer_Container_Product_Order_Service_External":                                 &datatypes.Container_Product_Order_Service_External{},
	"SoftLayer_Container_Product_Order_Software_Component_Virtual":                       &datatypes.Container_Product_Order_Software_Component_Virtual{},
	"SoftLayer_Container_Product_Order_Software_License":                                 &datatypes.Container_Product_Order_Software_License{},
	"SoftLayer_Container_Product_Order_Support":                                          &datatypes.Container_Product_Order_Support{},
	"SoftLayer_Container_Product_Order_User_Customer_External_Binding":                   &datatypes.Container_Product_Order_User_Customer_External_Binding{},
	"SoftLayer_Container_Product_Order_Virtual_DedicatedHost":                            &datatypes.Container_Product_Order_Virtual_DedicatedHost{},
	"SoftLayer_Container_Product_Order_Virtual_Disk_Image":                               &datatypes.Container_Product_Order_Virtual_Disk_Image{},
	"SoftLayer_Container_Product_Order_Virtual_Guest":                                    &datatypes.Container_Product_Order_Virtual_Guest{},
	"SoftLayer_Container_Product_Order_Virtual_Guest_Upgrade":                            &datatypes.Container_Product_Order_Virtual_Guest_Upgrade{},
	"SoftLayer_Container_Product_Order_Virtual_Guest_Vpc":                                &datatypes.Container_Product_Order_Virtual_Guest_Vpc{},
	"SoftLayer_Container_Product_Order_Virtual_Guest_Vpc_Upgrade":                        &datatypes.Container_Product_Order_Virtual_Guest_Vpc_Upgrade{},
	"SoftLayer_Container_Product_Order_Virtual_ReservedCapacity":                         &datatypes.Container_Product_Order_Virtual_ReservedCapacity{},
}
