// Code generated by counterfeiter. DO NOT EDIT.
package testhelpers

import (
	"sync"

	"github.com/softlayer/softlayer-go/sl"
	"github.ibm.com/SoftLayer/softlayer-cli/plugin/managers"
)

type FakeMetadataManager struct {
	CallAPIServiceStub        func(string, string, sl.Options, string) (string, error)
	callAPIServiceMutex       sync.RWMutex
	callAPIServiceArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 sl.Options
		arg4 string
	}
	callAPIServiceReturns struct {
		result1 string
		result2 error
	}
	callAPIServiceReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMetadataManager) CallAPIService(arg1 string, arg2 string, arg3 sl.Options, arg4 string) (string, error) {
	fake.callAPIServiceMutex.Lock()
	ret, specificReturn := fake.callAPIServiceReturnsOnCall[len(fake.callAPIServiceArgsForCall)]
	fake.callAPIServiceArgsForCall = append(fake.callAPIServiceArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 sl.Options
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.CallAPIServiceStub
	fakeReturns := fake.callAPIServiceReturns
	fake.recordInvocation("CallAPIService", []interface{}{arg1, arg2, arg3, arg4})
	fake.callAPIServiceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMetadataManager) CallAPIServiceCallCount() int {
	fake.callAPIServiceMutex.RLock()
	defer fake.callAPIServiceMutex.RUnlock()
	return len(fake.callAPIServiceArgsForCall)
}

func (fake *FakeMetadataManager) CallAPIServiceCalls(stub func(string, string, sl.Options, string) (string, error)) {
	fake.callAPIServiceMutex.Lock()
	defer fake.callAPIServiceMutex.Unlock()
	fake.CallAPIServiceStub = stub
}

func (fake *FakeMetadataManager) CallAPIServiceArgsForCall(i int) (string, string, sl.Options, string) {
	fake.callAPIServiceMutex.RLock()
	defer fake.callAPIServiceMutex.RUnlock()
	argsForCall := fake.callAPIServiceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeMetadataManager) CallAPIServiceReturns(result1 string, result2 error) {
	fake.callAPIServiceMutex.Lock()
	defer fake.callAPIServiceMutex.Unlock()
	fake.CallAPIServiceStub = nil
	fake.callAPIServiceReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeMetadataManager) CallAPIServiceReturnsOnCall(i int, result1 string, result2 error) {
	fake.callAPIServiceMutex.Lock()
	defer fake.callAPIServiceMutex.Unlock()
	fake.CallAPIServiceStub = nil
	if fake.callAPIServiceReturnsOnCall == nil {
		fake.callAPIServiceReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.callAPIServiceReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeMetadataManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.callAPIServiceMutex.RLock()
	defer fake.callAPIServiceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMetadataManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ managers.MetadataManager = new(FakeMetadataManager)
