// Code generated by counterfeiter. DO NOT EDIT.
package testhelpers

import (
	"sync"

	"github.com/softlayer/softlayer-go/datatypes"
	"github.ibm.com/SoftLayer/softlayer-cli/plugin/managers"
)

type FakeAutoScaleManager struct {
	GetScaleGroupStub        func(int, string) (datatypes.Scale_Group, error)
	getScaleGroupMutex       sync.RWMutex
	getScaleGroupArgsForCall []struct {
		arg1 int
		arg2 string
	}
	getScaleGroupReturns struct {
		result1 datatypes.Scale_Group
		result2 error
	}
	getScaleGroupReturnsOnCall map[int]struct {
		result1 datatypes.Scale_Group
		result2 error
	}
	ListScaleGroupsStub        func(string) ([]datatypes.Scale_Group, error)
	listScaleGroupsMutex       sync.RWMutex
	listScaleGroupsArgsForCall []struct {
		arg1 string
	}
	listScaleGroupsReturns struct {
		result1 []datatypes.Scale_Group
		result2 error
	}
	listScaleGroupsReturnsOnCall map[int]struct {
		result1 []datatypes.Scale_Group
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAutoScaleManager) GetScaleGroup(arg1 int, arg2 string) (datatypes.Scale_Group, error) {
	fake.getScaleGroupMutex.Lock()
	ret, specificReturn := fake.getScaleGroupReturnsOnCall[len(fake.getScaleGroupArgsForCall)]
	fake.getScaleGroupArgsForCall = append(fake.getScaleGroupArgsForCall, struct {
		arg1 int
		arg2 string
	}{arg1, arg2})
	stub := fake.GetScaleGroupStub
	fakeReturns := fake.getScaleGroupReturns
	fake.recordInvocation("GetScaleGroup", []interface{}{arg1, arg2})
	fake.getScaleGroupMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAutoScaleManager) GetScaleGroupCallCount() int {
	fake.getScaleGroupMutex.RLock()
	defer fake.getScaleGroupMutex.RUnlock()
	return len(fake.getScaleGroupArgsForCall)
}

func (fake *FakeAutoScaleManager) GetScaleGroupCalls(stub func(int, string) (datatypes.Scale_Group, error)) {
	fake.getScaleGroupMutex.Lock()
	defer fake.getScaleGroupMutex.Unlock()
	fake.GetScaleGroupStub = stub
}

func (fake *FakeAutoScaleManager) GetScaleGroupArgsForCall(i int) (int, string) {
	fake.getScaleGroupMutex.RLock()
	defer fake.getScaleGroupMutex.RUnlock()
	argsForCall := fake.getScaleGroupArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAutoScaleManager) GetScaleGroupReturns(result1 datatypes.Scale_Group, result2 error) {
	fake.getScaleGroupMutex.Lock()
	defer fake.getScaleGroupMutex.Unlock()
	fake.GetScaleGroupStub = nil
	fake.getScaleGroupReturns = struct {
		result1 datatypes.Scale_Group
		result2 error
	}{result1, result2}
}

func (fake *FakeAutoScaleManager) GetScaleGroupReturnsOnCall(i int, result1 datatypes.Scale_Group, result2 error) {
	fake.getScaleGroupMutex.Lock()
	defer fake.getScaleGroupMutex.Unlock()
	fake.GetScaleGroupStub = nil
	if fake.getScaleGroupReturnsOnCall == nil {
		fake.getScaleGroupReturnsOnCall = make(map[int]struct {
			result1 datatypes.Scale_Group
			result2 error
		})
	}
	fake.getScaleGroupReturnsOnCall[i] = struct {
		result1 datatypes.Scale_Group
		result2 error
	}{result1, result2}
}

func (fake *FakeAutoScaleManager) ListScaleGroups(arg1 string) ([]datatypes.Scale_Group, error) {
	fake.listScaleGroupsMutex.Lock()
	ret, specificReturn := fake.listScaleGroupsReturnsOnCall[len(fake.listScaleGroupsArgsForCall)]
	fake.listScaleGroupsArgsForCall = append(fake.listScaleGroupsArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ListScaleGroupsStub
	fakeReturns := fake.listScaleGroupsReturns
	fake.recordInvocation("ListScaleGroups", []interface{}{arg1})
	fake.listScaleGroupsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAutoScaleManager) ListScaleGroupsCallCount() int {
	fake.listScaleGroupsMutex.RLock()
	defer fake.listScaleGroupsMutex.RUnlock()
	return len(fake.listScaleGroupsArgsForCall)
}

func (fake *FakeAutoScaleManager) ListScaleGroupsCalls(stub func(string) ([]datatypes.Scale_Group, error)) {
	fake.listScaleGroupsMutex.Lock()
	defer fake.listScaleGroupsMutex.Unlock()
	fake.ListScaleGroupsStub = stub
}

func (fake *FakeAutoScaleManager) ListScaleGroupsArgsForCall(i int) string {
	fake.listScaleGroupsMutex.RLock()
	defer fake.listScaleGroupsMutex.RUnlock()
	argsForCall := fake.listScaleGroupsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAutoScaleManager) ListScaleGroupsReturns(result1 []datatypes.Scale_Group, result2 error) {
	fake.listScaleGroupsMutex.Lock()
	defer fake.listScaleGroupsMutex.Unlock()
	fake.ListScaleGroupsStub = nil
	fake.listScaleGroupsReturns = struct {
		result1 []datatypes.Scale_Group
		result2 error
	}{result1, result2}
}

func (fake *FakeAutoScaleManager) ListScaleGroupsReturnsOnCall(i int, result1 []datatypes.Scale_Group, result2 error) {
	fake.listScaleGroupsMutex.Lock()
	defer fake.listScaleGroupsMutex.Unlock()
	fake.ListScaleGroupsStub = nil
	if fake.listScaleGroupsReturnsOnCall == nil {
		fake.listScaleGroupsReturnsOnCall = make(map[int]struct {
			result1 []datatypes.Scale_Group
			result2 error
		})
	}
	fake.listScaleGroupsReturnsOnCall[i] = struct {
		result1 []datatypes.Scale_Group
		result2 error
	}{result1, result2}
}

func (fake *FakeAutoScaleManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getScaleGroupMutex.RLock()
	defer fake.getScaleGroupMutex.RUnlock()
	fake.listScaleGroupsMutex.RLock()
	defer fake.listScaleGroupsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAutoScaleManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ managers.AutoScaleManager = new(FakeAutoScaleManager)
