// Code generated by counterfeiter. DO NOT EDIT.
package testhelpers

import (
	"sync"

	"github.com/softlayer/softlayer-go/datatypes"
	"github.ibm.com/SoftLayer/softlayer-cli/plugin/managers"
)

type FakeAccountManager struct {
	GetBandwidthPoolServersStub        func(int) (int, error)
	getBandwidthPoolServersMutex       sync.RWMutex
	getBandwidthPoolServersArgsForCall []struct {
		arg1 int
	}
	getBandwidthPoolServersReturns struct {
		result1 int
		result2 error
	}
	getBandwidthPoolServersReturnsOnCall map[int]struct {
		result1 int
		result2 error
	}
	GetBandwidthPoolsStub        func() ([]datatypes.Network_Bandwidth_Version1_Allotment, error)
	getBandwidthPoolsMutex       sync.RWMutex
	getBandwidthPoolsArgsForCall []struct {
	}
	getBandwidthPoolsReturns struct {
		result1 []datatypes.Network_Bandwidth_Version1_Allotment
		result2 error
	}
	getBandwidthPoolsReturnsOnCall map[int]struct {
		result1 []datatypes.Network_Bandwidth_Version1_Allotment
		result2 error
	}
	GetInvoiceDetailStub        func(int) ([]datatypes.Billing_Invoice_Item, error)
	getInvoiceDetailMutex       sync.RWMutex
	getInvoiceDetailArgsForCall []struct {
		arg1 int
	}
	getInvoiceDetailReturns struct {
		result1 []datatypes.Billing_Invoice_Item
		result2 error
	}
	getInvoiceDetailReturnsOnCall map[int]struct {
		result1 []datatypes.Billing_Invoice_Item
		result2 error
	}
	SummaryByDatacenterStub        func() (map[string]map[string]int, error)
	summaryByDatacenterMutex       sync.RWMutex
	summaryByDatacenterArgsForCall []struct {
	}
	summaryByDatacenterReturns struct {
		result1 map[string]map[string]int
		result2 error
	}
	summaryByDatacenterReturnsOnCall map[int]struct {
		result1 map[string]map[string]int
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAccountManager) GetBandwidthPoolServers(arg1 int) (int, error) {
	fake.getBandwidthPoolServersMutex.Lock()
	ret, specificReturn := fake.getBandwidthPoolServersReturnsOnCall[len(fake.getBandwidthPoolServersArgsForCall)]
	fake.getBandwidthPoolServersArgsForCall = append(fake.getBandwidthPoolServersArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.GetBandwidthPoolServersStub
	fakeReturns := fake.getBandwidthPoolServersReturns
	fake.recordInvocation("GetBandwidthPoolServers", []interface{}{arg1})
	fake.getBandwidthPoolServersMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAccountManager) GetBandwidthPoolServersCallCount() int {
	fake.getBandwidthPoolServersMutex.RLock()
	defer fake.getBandwidthPoolServersMutex.RUnlock()
	return len(fake.getBandwidthPoolServersArgsForCall)
}

func (fake *FakeAccountManager) GetBandwidthPoolServersCalls(stub func(int) (int, error)) {
	fake.getBandwidthPoolServersMutex.Lock()
	defer fake.getBandwidthPoolServersMutex.Unlock()
	fake.GetBandwidthPoolServersStub = stub
}

func (fake *FakeAccountManager) GetBandwidthPoolServersArgsForCall(i int) int {
	fake.getBandwidthPoolServersMutex.RLock()
	defer fake.getBandwidthPoolServersMutex.RUnlock()
	argsForCall := fake.getBandwidthPoolServersArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAccountManager) GetBandwidthPoolServersReturns(result1 int, result2 error) {
	fake.getBandwidthPoolServersMutex.Lock()
	defer fake.getBandwidthPoolServersMutex.Unlock()
	fake.GetBandwidthPoolServersStub = nil
	fake.getBandwidthPoolServersReturns = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAccountManager) GetBandwidthPoolServersReturnsOnCall(i int, result1 int, result2 error) {
	fake.getBandwidthPoolServersMutex.Lock()
	defer fake.getBandwidthPoolServersMutex.Unlock()
	fake.GetBandwidthPoolServersStub = nil
	if fake.getBandwidthPoolServersReturnsOnCall == nil {
		fake.getBandwidthPoolServersReturnsOnCall = make(map[int]struct {
			result1 int
			result2 error
		})
	}
	fake.getBandwidthPoolServersReturnsOnCall[i] = struct {
		result1 int
		result2 error
	}{result1, result2}
}

func (fake *FakeAccountManager) GetBandwidthPools() ([]datatypes.Network_Bandwidth_Version1_Allotment, error) {
	fake.getBandwidthPoolsMutex.Lock()
	ret, specificReturn := fake.getBandwidthPoolsReturnsOnCall[len(fake.getBandwidthPoolsArgsForCall)]
	fake.getBandwidthPoolsArgsForCall = append(fake.getBandwidthPoolsArgsForCall, struct {
	}{})
	stub := fake.GetBandwidthPoolsStub
	fakeReturns := fake.getBandwidthPoolsReturns
	fake.recordInvocation("GetBandwidthPools", []interface{}{})
	fake.getBandwidthPoolsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAccountManager) GetBandwidthPoolsCallCount() int {
	fake.getBandwidthPoolsMutex.RLock()
	defer fake.getBandwidthPoolsMutex.RUnlock()
	return len(fake.getBandwidthPoolsArgsForCall)
}

func (fake *FakeAccountManager) GetBandwidthPoolsCalls(stub func() ([]datatypes.Network_Bandwidth_Version1_Allotment, error)) {
	fake.getBandwidthPoolsMutex.Lock()
	defer fake.getBandwidthPoolsMutex.Unlock()
	fake.GetBandwidthPoolsStub = stub
}

func (fake *FakeAccountManager) GetBandwidthPoolsReturns(result1 []datatypes.Network_Bandwidth_Version1_Allotment, result2 error) {
	fake.getBandwidthPoolsMutex.Lock()
	defer fake.getBandwidthPoolsMutex.Unlock()
	fake.GetBandwidthPoolsStub = nil
	fake.getBandwidthPoolsReturns = struct {
		result1 []datatypes.Network_Bandwidth_Version1_Allotment
		result2 error
	}{result1, result2}
}

func (fake *FakeAccountManager) GetBandwidthPoolsReturnsOnCall(i int, result1 []datatypes.Network_Bandwidth_Version1_Allotment, result2 error) {
	fake.getBandwidthPoolsMutex.Lock()
	defer fake.getBandwidthPoolsMutex.Unlock()
	fake.GetBandwidthPoolsStub = nil
	if fake.getBandwidthPoolsReturnsOnCall == nil {
		fake.getBandwidthPoolsReturnsOnCall = make(map[int]struct {
			result1 []datatypes.Network_Bandwidth_Version1_Allotment
			result2 error
		})
	}
	fake.getBandwidthPoolsReturnsOnCall[i] = struct {
		result1 []datatypes.Network_Bandwidth_Version1_Allotment
		result2 error
	}{result1, result2}
}

func (fake *FakeAccountManager) GetInvoiceDetail(arg1 int) ([]datatypes.Billing_Invoice_Item, error) {
	fake.getInvoiceDetailMutex.Lock()
	ret, specificReturn := fake.getInvoiceDetailReturnsOnCall[len(fake.getInvoiceDetailArgsForCall)]
	fake.getInvoiceDetailArgsForCall = append(fake.getInvoiceDetailArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.GetInvoiceDetailStub
	fakeReturns := fake.getInvoiceDetailReturns
	fake.recordInvocation("GetInvoiceDetail", []interface{}{arg1})
	fake.getInvoiceDetailMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAccountManager) GetInvoiceDetailCallCount() int {
	fake.getInvoiceDetailMutex.RLock()
	defer fake.getInvoiceDetailMutex.RUnlock()
	return len(fake.getInvoiceDetailArgsForCall)
}

func (fake *FakeAccountManager) GetInvoiceDetailCalls(stub func(int) ([]datatypes.Billing_Invoice_Item, error)) {
	fake.getInvoiceDetailMutex.Lock()
	defer fake.getInvoiceDetailMutex.Unlock()
	fake.GetInvoiceDetailStub = stub
}

func (fake *FakeAccountManager) GetInvoiceDetailArgsForCall(i int) int {
	fake.getInvoiceDetailMutex.RLock()
	defer fake.getInvoiceDetailMutex.RUnlock()
	argsForCall := fake.getInvoiceDetailArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAccountManager) GetInvoiceDetailReturns(result1 []datatypes.Billing_Invoice_Item, result2 error) {
	fake.getInvoiceDetailMutex.Lock()
	defer fake.getInvoiceDetailMutex.Unlock()
	fake.GetInvoiceDetailStub = nil
	fake.getInvoiceDetailReturns = struct {
		result1 []datatypes.Billing_Invoice_Item
		result2 error
	}{result1, result2}
}

func (fake *FakeAccountManager) GetInvoiceDetailReturnsOnCall(i int, result1 []datatypes.Billing_Invoice_Item, result2 error) {
	fake.getInvoiceDetailMutex.Lock()
	defer fake.getInvoiceDetailMutex.Unlock()
	fake.GetInvoiceDetailStub = nil
	if fake.getInvoiceDetailReturnsOnCall == nil {
		fake.getInvoiceDetailReturnsOnCall = make(map[int]struct {
			result1 []datatypes.Billing_Invoice_Item
			result2 error
		})
	}
	fake.getInvoiceDetailReturnsOnCall[i] = struct {
		result1 []datatypes.Billing_Invoice_Item
		result2 error
	}{result1, result2}
}

func (fake *FakeAccountManager) SummaryByDatacenter() (map[string]map[string]int, error) {
	fake.summaryByDatacenterMutex.Lock()
	ret, specificReturn := fake.summaryByDatacenterReturnsOnCall[len(fake.summaryByDatacenterArgsForCall)]
	fake.summaryByDatacenterArgsForCall = append(fake.summaryByDatacenterArgsForCall, struct {
	}{})
	stub := fake.SummaryByDatacenterStub
	fakeReturns := fake.summaryByDatacenterReturns
	fake.recordInvocation("SummaryByDatacenter", []interface{}{})
	fake.summaryByDatacenterMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAccountManager) SummaryByDatacenterCallCount() int {
	fake.summaryByDatacenterMutex.RLock()
	defer fake.summaryByDatacenterMutex.RUnlock()
	return len(fake.summaryByDatacenterArgsForCall)
}

func (fake *FakeAccountManager) SummaryByDatacenterCalls(stub func() (map[string]map[string]int, error)) {
	fake.summaryByDatacenterMutex.Lock()
	defer fake.summaryByDatacenterMutex.Unlock()
	fake.SummaryByDatacenterStub = stub
}

func (fake *FakeAccountManager) SummaryByDatacenterReturns(result1 map[string]map[string]int, result2 error) {
	fake.summaryByDatacenterMutex.Lock()
	defer fake.summaryByDatacenterMutex.Unlock()
	fake.SummaryByDatacenterStub = nil
	fake.summaryByDatacenterReturns = struct {
		result1 map[string]map[string]int
		result2 error
	}{result1, result2}
}

func (fake *FakeAccountManager) SummaryByDatacenterReturnsOnCall(i int, result1 map[string]map[string]int, result2 error) {
	fake.summaryByDatacenterMutex.Lock()
	defer fake.summaryByDatacenterMutex.Unlock()
	fake.SummaryByDatacenterStub = nil
	if fake.summaryByDatacenterReturnsOnCall == nil {
		fake.summaryByDatacenterReturnsOnCall = make(map[int]struct {
			result1 map[string]map[string]int
			result2 error
		})
	}
	fake.summaryByDatacenterReturnsOnCall[i] = struct {
		result1 map[string]map[string]int
		result2 error
	}{result1, result2}
}

func (fake *FakeAccountManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getBandwidthPoolServersMutex.RLock()
	defer fake.getBandwidthPoolServersMutex.RUnlock()
	fake.getBandwidthPoolsMutex.RLock()
	defer fake.getBandwidthPoolsMutex.RUnlock()
	fake.getInvoiceDetailMutex.RLock()
	defer fake.getInvoiceDetailMutex.RUnlock()
	fake.summaryByDatacenterMutex.RLock()
	defer fake.summaryByDatacenterMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAccountManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ managers.AccountManager = new(FakeAccountManager)
