package main

import (
	"fmt"
	"os"
	"strings"
	"encoding/json"

	"text/template"
	// "sort"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	// "github.com/IBM-Cloud/ibm-cloud-cli-sdk/plugin"
	sl_plugin "github.ibm.com/SoftLayer/softlayer-cli/plugin"
)

var fileName string
var rootCmd = &cobra.Command{
	Use: "doc-gen",
	Short: "Generate the documentation for the sl plugin",
	RunE: func(Cmd *cobra.Command, args []string) error {
		CliDocs()
		return nil
	},
}

func main() {
	err := rootCmd.Execute()
	checkError(err)
	return
}

func checkError(err error) {
	if err != nil {
		panic(err)
	}
}

// For top level commands, like `sl account` or `sl hardware`
type SlCmdGroup struct {
	Name string
	CommandShortLink string
	Commands []SlCmdDoc
	Help string
}

// For specific commands
type SlCmdDoc struct {
	Name string
	CommandShortLink string
	Use string
	Flags []SlCmdFlag
	Help string
	LongHelp string
	Backtick string
	CommandPath string
}

// For a commands flags
type SlCmdFlag struct {
	Name string
	Help string
	Default string
}



// This function builds the documentation for IBMCLOUD docs
func CliDocs() {
	// fmt.Printf("IBMCLOUD SL Command Directory\n")
	SlCommands := sl_plugin.GetTopCobraCommand(nil, nil)
	CmdGroups := []SlCmdGroup{}
	for _, iCmd := range SlCommands.Commands() {
		shortName := strings.ReplaceAll(iCmd.Name(), " ", "_")
		shortName = strings.ReplaceAll(iCmd.Name(), "-", "_")
		thisCmdGroup := SlCmdGroup{
			Name: iCmd.Name(),
			CommandShortLink: fmt.Sprintf("sl_%v", shortName),
			Commands: nil,
			Help: iCmd.Short,

		}
		if len(iCmd.Commands()) > 0 {
			thisCmdGroup.Commands = buildSlCmdDoc(iCmd)
		}
		PrintMakrdown(thisCmdGroup)
		CmdGroups = append(CmdGroups, thisCmdGroup)
	}
	jOut, err := json.MarshalIndent(CmdGroups, "", "  ")
	os.WriteFile("sl.json", jOut, 0755)
	checkError(err)
	// fmt.Println(string(jOut))
}

// Generates the Markdown
func PrintMakrdown(cmd SlCmdGroup) {

	var cmdTemplate = `<!-- THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT -->
# ibmcloud sl {{.Name}}
{: #{{.CommandShortLink}}}

{{.Help}}

{{range .Commands}}
## ibmcloud {{.CommandPath}}
{: #{{.CommandShortLink}}}

{{.Help}}

{{.LongHelp}}

{{.Backtick}}bash
ibmcloud {{.Use}}
{{.Backtick}}
{: codeblock}

{{if .Flags}}
**Command options**:
{{range .Flags}}
--{{.Name}}
:    {{.Help}}
{{end}}{{end}}{{end}}`

	mdTemplate, err := template.New("cmd template").Parse(cmdTemplate)
	checkError(err)
	filename := fmt.Sprintf("%v.md", cmd.CommandShortLink)
	outfile, err := os.Create(filename)
	defer outfile.Close()
	err = mdTemplate.Execute(outfile, cmd)
	checkError(err)

}

func getLongHelp(helpString string) string {
	helpString = strings.ReplaceAll(helpString, "${COMMAND_NAME}", "ibmcloud")
	helpString = strings.ReplaceAll(helpString, "EXAMPLE:", "**Examples**:\n")
	return helpString
}

func buildSlCmdDoc(topCommand *cobra.Command) []SlCmdDoc {
	docs := []SlCmdDoc{}
	for _, iCmd := range topCommand.Commands() {
		shortName := fmt.Sprintf("sl_%s_%s", topCommand.Name(), iCmd.Name())
		shortName = strings.ReplaceAll(shortName, " ", "_")
		shortName = strings.ReplaceAll(shortName, "-", "_")
		longHelp := getLongHelp(iCmd.Long)
		thisDoc := SlCmdDoc{
			Name: iCmd.Name(),
			CommandShortLink: shortName,
			CommandPath: iCmd.CommandPath(),
			Use: iCmd.UseLine(),
			Flags: nil,
			Help: iCmd.Short,
			LongHelp: longHelp,
			Backtick:  "```",
		}
		thisDoc.Flags = buildSlCmdFlag(iCmd)

		docs = append(docs, thisDoc)
	}
	return docs
}

func buildSlCmdFlag(topCommand *cobra.Command) []SlCmdFlag {
	flags := []SlCmdFlag{}
	flagSet := topCommand.Flags()
	flagSet.VisitAll(func(pflag *pflag.Flag) {
		flagName := pflag.Name
		if pflag.Shorthand != "" {
			flagName = fmt.Sprintf("%s, %s", pflag.Shorthand, flagName)
		}
		thisFlag := SlCmdFlag{
			Name:flagName,
			Help: pflag.Usage,
			Default: pflag.DefValue,
		}
		flags = append(flags, thisFlag)
	})
	return flags
}
